# USAGE INSTSRUCTIONS
# 
# Build image (run this in the main directory (where .git folder is)):
# docker build -t nemocrys/dolfinx-openfoam -f ./docker/Dockerfile .
#
# Run image:
# docker run -it --rm nemocrys/dolfinx-openfoam:vX.X.X bash
#
# Run image and map current directory to home/workdir on Linux:
# docker run -it --rm -v $PWD:/home/workdir -e LOCAL_UID=$(id -u $USER) -e LOCAL_GID=$(id -g $USER) nemocrys/dolfinx-openfoam bash
# and on Windows:
# docker run -it --rm -v ${PWD}:/home/workdir nemocrys/dolfinx-openfoam bash

FROM ubuntu:20.04

# deactivate interations -> no question for geolocation
ENV DEBIAN_FRONTEND=noninteractive 

# Set the working directory to /home
WORKDIR /home

# Install python and required packages
RUN apt-get update && \
    apt-get -y install \
    python3=3.8.* \
    python3-pip=20.0.* &&\
    pip3 install \
        meshio==4.4.*\
        numpy==1.20.*\
        matplotlib==3.4.*\
        scipy==1.6.*\
        pandas==1.2.*\
        pyyaml==5.4.*

# Install gmsh & dependencies
# istructions found here: https://fenicsproject.discourse.group/t/problem-with-installation-of-latest-gmsh-4-6-0-via-pip/4078/2
ARG GMSH_VERSION=4.8.4
RUN apt-get install -y \
        wget \
        libglu1 \
        libxrender1  \
        libxcursor-dev \
        libxft-dev \
        libxinerama-dev && \
    wget -nc  http://gmsh.info/bin/Linux/gmsh-${GMSH_VERSION}-Linux64-sdk.tgz && \
    tar -xf gmsh-${GMSH_VERSION}-Linux64-sdk.tgz && \
    rm gmsh-${GMSH_VERSION}-Linux64-sdk.tgz
ENV PYTHONPATH=/home/gmsh-${GMSH_VERSION}-Linux64-sdk/lib:$PYTHONPATH
ENV PATH=/home/gmsh-${GMSH_VERSION}-Linux64-sdk/bin:$PATH


# install DOLFINx
# instructions copied from https://github.com/FEniCS/dolfinx/blob/main/docker/Dockerfile
# TODO



RUN mkdir /home/workdir
WORKDIR /home/workdir

# modify user id and group
# see https://techflare.blog/permission-problems-in-bind-mount-in-docker-volume/
COPY  ./docker/entrypoint.sh /
RUN apt-get -y install gosu 
ENTRYPOINT [ "/entrypoint.sh" ]
